### ISSUE TITLE
Define max grenades in defs.h

### ISSUE THREAD

**Issue by lordee** [FortressOne/server-qwprogs#33]
Similar to PC_SOLDIER_MAXAMMO_ROCKET, create max grenade defs and apply to codebase

**Comment by drzel** [comment]
I started to do this, but... well it's a bigger job than it seems. We really should be creating two `PC_<CLASS>_MAX_GRENS_<NO>` constants for each class.

The problem is they're not actually being called, so would be misleading. Changing them wouldn't affect the maxs. So I'd then need to set up a unnecessary case statement inside `GetMaxGrenades()`.

Anyway I did a partial refactor. Not sure if it should go in or not. Would be interested to hear your thoughts.
